/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeAudio */

#ifndef _Included_com_limo_emumod_bridge_NativeAudio
#define _Included_com_limo_emumod_bridge_NativeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeAudio
 * Method:    bufSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_limo_emumod_bridge_NativeAudio_bufSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_limo_emumod_bridge_NativeAudio
 * Method:    update
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_bridge_NativeAudio_update
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
