/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_client_bridge_NativeClient */

#ifndef _Included_com_limo_emumod_client_bridge_NativeClient
#define _Included_com_limo_emumod_client_bridge_NativeClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    init
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_client_bridge_NativeClient_init
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    deinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_client_bridge_NativeClient_deinit
  (JNIEnv *, jclass);

/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_client_bridge_NativeClient_isConnected
  (JNIEnv *, jclass);

/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    screenChanged
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_client_bridge_NativeClient_screenChanged
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    registerId
 * Signature: (IIIIJI)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_client_bridge_NativeClient_registerId
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jint);

/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    unregisterId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_client_bridge_NativeClient_unregisterId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_limo_emumod_client_bridge_NativeClient
 * Method:    sendControls
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_client_bridge_NativeClient_sendControls
  (JNIEnv *, jclass, jint, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
