/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeGenericConsole */

#ifndef _Included_com_limo_emumod_bridge_NativeGenericConsole
#define _Included_com_limo_emumod_bridge_NativeGenericConsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeGenericConsole
 * Method:    register
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_limo_emumod_bridge_NativeGenericConsole_register
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_limo_emumod_bridge_NativeGenericConsole
 * Method:    unregister
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_bridge_NativeGenericConsole_unregister
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_limo_emumod_bridge_NativeGenericConsole
 * Method:    start
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_bridge_NativeGenericConsole_start
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
