/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeServer */

#ifndef _Included_com_limo_emumod_bridge_NativeServer
#define _Included_com_limo_emumod_bridge_NativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeServer
 * Method:    init
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_bridge_NativeServer_init
  (JNIEnv *, jclass, jint, jstring, jobjectArray);

/*
 * Class:     com_limo_emumod_bridge_NativeServer
 * Method:    deinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_bridge_NativeServer_deinit
  (JNIEnv *, jclass);

/*
 * Class:     com_limo_emumod_bridge_NativeServer
 * Method:    generateToken
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_limo_emumod_bridge_NativeServer_generateToken
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
