/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeDisplay */

#ifndef _Included_com_limo_emumod_bridge_NativeDisplay
#define _Included_com_limo_emumod_bridge_NativeDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeDisplay
 * Method:    update
 * Signature: (Lcom/sun/jna/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_bridge_NativeDisplay_update
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
