/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeGameBoy */

#ifndef _Included_com_limo_emumod_bridge_NativeGameBoy
#define _Included_com_limo_emumod_bridge_NativeGameBoy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeGameBoy
 * Method:    init
 * Signature: ()Lcom/sun/jna/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_limo_emumod_bridge_NativeGameBoy_init
  (JNIEnv *, jclass);

/*
 * Class:     com_limo_emumod_bridge_NativeGameBoy
 * Method:    load
 * Signature: (Lcom/sun/jna/Pointer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_bridge_NativeGameBoy_load
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
