/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeDisplay */

#ifndef _Included_com_limo_emumod_bridge_NativeDisplay
#define _Included_com_limo_emumod_bridge_NativeDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeDisplay
 * Method:    bufSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_limo_emumod_bridge_NativeDisplay_bufSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_limo_emumod_bridge_NativeDisplay
 * Method:    hasChanged
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_limo_emumod_bridge_NativeDisplay_hasChanged
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_limo_emumod_bridge_NativeDisplay
 * Method:    update
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_limo_emumod_bridge_NativeDisplay_update
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
