/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limo_emumod_bridge_NativeUtil */

#ifndef _Included_com_limo_emumod_bridge_NativeUtil
#define _Included_com_limo_emumod_bridge_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limo_emumod_bridge_NativeUtil
 * Method:    nativeUUID
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_limo_emumod_bridge_NativeUtil_nativeUUID
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_limo_emumod_bridge_NativeUtil
 * Method:    mostSignificantBits
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_limo_emumod_bridge_NativeUtil_mostSignificantBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_limo_emumod_bridge_NativeUtil
 * Method:    leastSignificantBits
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_limo_emumod_bridge_NativeUtil_leastSignificantBits
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
